import {context,numberSpec,signed} from '../shared.js';
const IDS=['kin_04','kin_06','kin_07','kin_08','kin_12','kin_13','kin_14'];
export const kinematicsGenerator={key:'physics.kinematics',version:1,title:'Кинематика',competencyIds:IDS,generate(args){return context(this,args,(random,difficulty,options)=>{
  const mode=options.mode||random.pick(['coordinate','displacement','path']),x0=random.int(-8,8),velocity=(random.int(1,4+difficulty))*(random.bool()?1:-1),time=random.int(2,4+difficulty),x=x0+velocity*time,displacement=velocity*time;
  if(mode==='speed')return {topic:'Средняя скорость',prompt:`Тело прошло ${Math.abs(displacement)} м за ${time} с. Найдите среднюю скорость движения.`,answerSpec:numberSpec(Math.abs(velocity)),hints:['Используйте v=S/t.','Разделите путь на время.','Единица ответа — м/с.'],solution:[`v=${Math.abs(displacement)}/${time}=${Math.abs(velocity)} м/с.`],parameters:{mode,x0,velocity,time,x,displacement}};
  if(mode==='direction')return {topic:'Знак проекции скорости',prompt:`Координата тела задана формулой x=${x0} ${signed(velocity)}t. Какой знак имеет проекция скорости? Ответьте «положительный» или «отрицательный».`,answerSpec:{type:'choice',value:velocity>0?'положительный':'отрицательный'},hints:['Сравните формулу с x=x₀+vₓt.','Коэффициент при t — это проекция скорости.','Определите знак коэффициента при t.'],solution:[`vₓ=${velocity} м/с, поэтому знак ${velocity>0?'положительный':'отрицательный'}.`],parameters:{mode,x0,velocity,time,x,displacement}};
  if(mode==='displacement')return {topic:'Перемещение',prompt:`Тело движется по прямой из координаты x₀=${x0} м со скоростью vₓ=${velocity} м/с в течение ${time} с. Найдите проекцию перемещения.`,answerSpec:numberSpec(displacement),hints:['Проекция перемещения равна vₓt.','Сохраните знак проекции скорости.','Умножьте скорость на время.'],solution:[`Δx=${velocity}·${time}=${displacement} м.`],parameters:{mode,x0,velocity,time,x,displacement}};
  if(mode==='path')return {topic:'Путь и перемещение',prompt:`Тело движется без разворота со скоростью ${Math.abs(velocity)} м/с в течение ${time} с. Какой путь оно прошло?`,answerSpec:numberSpec(Math.abs(displacement)),hints:['Путь — неотрицательная длина траектории.','При движении без разворота S=|v|t.','Используйте модуль скорости.'],solution:[`S=${Math.abs(velocity)}·${time}=${Math.abs(displacement)} м.`],parameters:{mode,x0,velocity,time,x,displacement}};
  return {topic:'Уравнение координаты',prompt:`Движение задано формулой x=${x0} ${signed(velocity)}t (м). Найдите координату через ${time} с.`,answerSpec:numberSpec(x),hints:['Подставьте время вместо t.','Соблюдайте знак проекции скорости.',`Вычислите ${x0}+(${velocity})·${time}.`],solution:[`x=${x0}+(${velocity})·${time}=${x} м.`],parameters:{mode:'coordinate',x0,velocity,time,x,displacement}};
  });}};
export default kinematicsGenerator;
