export const RECENT_LIMIT = 3;
export const ARCHIVE_PAGE_SIZE = 10;
const MOBILE_QUERY = '(max-width:900px)';
const FOCUSABLE = 'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';

export function assertRegistry(lessons){
  if(!Array.isArray(lessons)) throw new TypeError('LESSONS must be an array');
  const dates=new Set(), hrefs=new Set();
  let previous=Infinity;
  for(const lesson of lessons){
    if(!lesson?.date||!lesson?.href||!lesson?.title) throw new Error('Invalid lesson registry record');
    for(const outcome of lesson.outcomes||[]){
      if(!outcome?.label||!Number.isFinite(Number(outcome.level)))throw new Error(`Invalid lesson outcome: ${lesson.date}`);
      if(outcome.competencyId!==undefined&&!/^[a-z0-9][a-z0-9_-]*$/i.test(outcome.competencyId))throw new Error(`Invalid competencyId in lesson ${lesson.date}`);
    }
    const stamp=Date.parse(`${lesson.date}T00:00:00Z`);
    if(!Number.isFinite(stamp)||stamp>previous) throw new Error('LESSONS must be newest-first');
    previous=stamp;
    if(dates.has(lesson.date)) throw new Error(`Duplicate lesson date: ${lesson.date}`);
    if(hrefs.has(lesson.href)) throw new Error(`Duplicate lesson href: ${lesson.href}`);
    dates.add(lesson.date);hrefs.add(lesson.href);
  }
  return true;
}
export const getLatestLesson=lessons=>lessons[0]||null;
export const getRecentLessons=(lessons,limit=RECENT_LIMIT)=>lessons.slice(0,limit);
export function paginateArchive(lessons,pageIndex=0,pageSize=ARCHIVE_PAGE_SIZE){
  const archive=lessons.slice(RECENT_LIMIT), count=Math.max(1,Math.ceil(archive.length/pageSize));
  const safe=Math.max(0,Math.min(pageIndex,count-1));
  return {items:archive.slice(safe*pageSize,(safe+1)*pageSize),pageIndex:safe,pageCount:count,total:archive.length};
}
export function formatShortDate(value){const [y,m,d]=value.split('-');return `${d}.${m}`;}
export function formatLongDateRu(value){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`));}
const byId=id=>document.getElementById(id);
const setText=(id,value)=>{const node=byId(id);if(node)node.textContent=value??'';};
function configureLink(id,href,{newTab=false}={}){const link=byId(id);if(!link)return;link.hidden=!href;if(!href){link.removeAttribute('href');return;}link.href=href;if(newTab){link.target='_blank';link.rel='noopener';}else{link.removeAttribute('target');link.removeAttribute('rel');}}
function lessonLink(lesson,index){const a=document.createElement('a');a.className=`lesson-link${index===0?' active':''}`;a.href=lesson.href;const d=document.createElement('span');d.className='lesson-date';d.textContent=formatShortDate(lesson.date);const copy=document.createElement('span');const strong=document.createElement('strong');strong.textContent=lesson.navTitle||lesson.title;const small=document.createElement('small');small.textContent=index===0?'последнее занятие':lesson.navSubtitle||lesson.title;copy.append(strong,small);const arrow=document.createElement('span');arrow.className='lesson-arrow';arrow.ariaHidden='true';arrow.textContent='→';a.append(d,copy,arrow);return a;}
function renderLatest(lessons){const lesson=getLatestLesson(lessons);if(!lesson)return;setText('latestLessonEyebrow',`Последнее занятие · ${formatLongDateRu(lesson.date)}`);setText('lesson-title',lesson.title);setText('lessonLead',lesson.summary||'Материалы занятия доступны в кабинете.');setText('mapUpdatedDate',`Кабинет обновлён ${formatLongDateRu(lesson.date)}`);const topics=byId('lessonTopics');if(topics)topics.replaceChildren(...(lesson.topics||[]).map(text=>{const span=document.createElement('span');span.className='chip';span.textContent=text;return span;}));const status=byId('latestLessonStatus');if(status){const heading=document.createElement('p');heading.className='status-title';heading.textContent='После урока';const rows=(lesson.outcomes||[]).map(o=>{const row=document.createElement('div');row.className=`outcome ${o.tone||'process'}`;row.innerHTML=`<span class="outcome-mark">${o.tone==='good'?'✓':o.tone==='alert'?'!':'◐'}</span><span></span><b></b>`;row.children[1].textContent=o.label;row.children[2].textContent=`${o.level}/4`;return row;});status.replaceChildren(heading,...rows);}const cta=byId('latestLessonCta');if(cta){cta.href=lesson.href;cta.hidden=false;}const m=lesson.materials||{};configureLink('latestReviewLink',m.review,{newTab:true});configureLink('latestPdfLink',m.pdf);configureLink('latestTexLink',m.tex);}
function renderRecent(lessons){const recent=getRecentLessons(lessons);byId('recentLessons')?.replaceChildren(...recent.map(lessonLink));setText('recentLessonCount',`${recent.length} свежих`);}
function setupArchive(lessons){let index=0;const render=()=>{const page=paginateArchive(lessons,index);index=page.pageIndex;const host=byId('archivePage');if(host){host.replaceChildren(...page.items.map(item=>{const a=document.createElement('a');a.className='archive-link';a.href=item.href;const time=document.createElement('time');time.dateTime=item.date;time.textContent=formatShortDate(item.date);const strong=document.createElement('strong');strong.textContent=item.title;a.append(time,strong);return a;}));host.setAttribute('aria-label',`Страница ${page.pageIndex+1} из ${page.pageCount}`);}setText('archivePageInfo',`${page.pageIndex+1} / ${page.pageCount}`);setText('archiveToggleMeta',`Ещё ${page.total} · по ${ARCHIVE_PAGE_SIZE} на странице`);if(byId('archivePrev'))byId('archivePrev').disabled=page.pageIndex===0;if(byId('archiveNext'))byId('archiveNext').disabled=page.pageIndex>=page.pageCount-1;if(byId('archiveToggle'))byId('archiveToggle').hidden=page.total===0;if(byId('archivePagination'))byId('archivePagination').hidden=page.total===0;};render();byId('archiveToggle')?.addEventListener('click',()=>{const t=byId('archiveToggle'),box=byId('archiveMore'),open=t.getAttribute('aria-expanded')==='true';t.setAttribute('aria-expanded',String(!open));box.hidden=open;});byId('archivePrev')?.addEventListener('click',()=>{if(index>0){index--;render();}});byId('archiveNext')?.addEventListener('click',()=>{const p=paginateArchive(lessons,index);if(index<p.pageCount-1){index++;render();}});}
function setInert(node,value){if(!node)return;node.inert=Boolean(value);value?node.setAttribute('inert',''):node.removeAttribute('inert');}
function setupDrawer(){const menu=byId('menuButton'),sidebar=byId('sidebar'),close=byId('sidebarClose'),backdrop=byId('sidebarBackdrop'),main=byId('content'),bar=document.querySelector('.mobile-bar');if(!menu||!sidebar||!backdrop)return;const media=matchMedia(MOBILE_QUERY);let opener=menu;const focusables=()=>[...sidebar.querySelectorAll(FOCUSABLE)].filter(n=>!n.closest('[hidden]')&&n.getClientRects().length);const normalize=()=>{document.body.classList.remove('sidebar-open');menu.setAttribute('aria-expanded','false');backdrop.hidden=true;setInert(main,false);setInert(bar,false);if(media.matches){setInert(sidebar,true);sidebar.setAttribute('aria-hidden','true');}else{setInert(sidebar,false);sidebar.removeAttribute('aria-hidden');}};const toggle=(open,{restore=true}={})=>{if(!media.matches){normalize();return;}if(open){opener=document.activeElement instanceof HTMLElement?document.activeElement:menu;setInert(sidebar,false);sidebar.setAttribute('aria-hidden','false');setInert(main,true);setInert(bar,true);document.body.classList.add('sidebar-open');menu.setAttribute('aria-expanded','true');backdrop.hidden=false;requestAnimationFrame(()=>{(close||focusables()[0])?.focus();});}else{document.body.classList.remove('sidebar-open');menu.setAttribute('aria-expanded','false');backdrop.hidden=true;setInert(main,false);setInert(bar,false);setInert(sidebar,true);sidebar.setAttribute('aria-hidden','true');if(restore)requestAnimationFrame(()=>opener?.focus?.());}};menu.addEventListener('click',()=>toggle(!document.body.classList.contains('sidebar-open')));close?.addEventListener('click',()=>toggle(false));backdrop.addEventListener('click',()=>toggle(false));sidebar.addEventListener('click',e=>{if(media.matches&&e.target.closest?.('a[href]'))setTimeout(()=>toggle(false,{restore:false}),0);});document.addEventListener('keydown',e=>{if(!media.matches||!document.body.classList.contains('sidebar-open'))return;if(e.key==='Escape'){e.preventDefault();toggle(false);return;}if(e.key!=='Tab')return;const nodes=focusables();if(!nodes.length){e.preventDefault();return;}const [first,last]=[nodes[0],nodes.at(-1)],active=document.activeElement;if(e.shiftKey&&(active===first||!sidebar.contains(active))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(active===last||!sidebar.contains(active))){e.preventDefault();first.focus();}});media.addEventListener?.('change',normalize);media.addListener?.(normalize);normalize();}
function setupTheme(key){const apply=value=>{if(value==='light')document.body.dataset.theme='light';else delete document.body.dataset.theme;try{localStorage.setItem(key,value);}catch(_){}};try{if(localStorage.getItem(key)==='light')document.body.dataset.theme='light';}catch(_){}document.querySelectorAll('#themeToggle,#mobileThemeToggle').forEach(btn=>btn.addEventListener('click',()=>apply(document.body.dataset.theme==='light'?'dark':'light')));}
function setupSummary(eventName){if(!eventName)return;addEventListener(eventName,e=>{const s=e.detail||{};setText('totalCount',s.total??'—');setText('evaluatedCount',s.evaluated??'—');setText('unseenCount',s.unseen??'—');setText('helpCount',s.help??'—');setText('confidentCount',s.confident??'—');setText('confidentCountMain',s.confident??'—');setText('processCount',s.process??'—');setText('processCountMain',s.process??'—');setText('masteredCount',s.mastered??'—');setText('masteredCountMain',s.mastered??'—');});}
export function initStudentDashboard({lessons,themeKey,summaryEvent}){assertRegistry(lessons);renderLatest(lessons);renderRecent(lessons);setupArchive(lessons);setupTheme(themeKey);setupDrawer();setupSummary(summaryEvent);}
